### PR TITLE
feat: Updating tfvars to simplify, and using for_each where possible

### PR DESCRIPTION
**Pull request by arehmandev**

### CODE REVIEW

**Comment by mscribellito** [comment]
Looks good for the most part. I did try to test with multiple/start jobs for different instances and only 1 set of start/stop jobs is attempting to be created and the other destroyed. Below is an example of what I was using for `jobs`:

```
  jobs =  {
    "mon-fri-8am-5pm" = {
      start     = "0 8 * * 1-5"
      stop      = "0 17 * * 1-5"
      instances = ["acme-db-1", "acme-db-2"]
      time_zone = null
    },
    "sat-sun-11am-3pm" = {
      start     = "0 11 * * 6-7"
      stop      = "0 15 * * 6-7"
      instances = ["acme-db-3", "acme-db-4"]
      time_zone = null
    }
  }
  ```

**Comment by arehmandev** [comment]
Apologies, I actually realised that just before I fell asleep, let me just go ahead and fix that

**Comment by arehmandev** [comment]
Give it a go now mate @mscribellito

**Review by mscribellito — APPROVED** [review]

**Comment by mscribellito** [comment]
Thanks @arehmandev - I like the changes and you taught me a few things :)

**Pull request merged**
